version: "2"
services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "dreamvids"

